### ISSUE TITLE
Bad Credential

### ISSUE THREAD

**Issue by sanjeet2014mca** [sothawo/SecuRest#1]
Hi i want to imlement SecuRest getting issue: 
Passing curl command on windows 
---------------------------------------------
Using default security password: dfd7dfc7-e76a-451a-b24c-ca4308324c24
Request:-
curl user:dfd7dfc7-e76a-451a-b24c-ca4308324c24@localhost:8080/service/echo/hello
![securest](https://cloud.githubusercontent.com/assets/19646873/15745595/3ed890ca-28f0-11e6-994d-09d11d99c2f4.PNG)
Response:-
{"timestamp":1464872036833,"status":401,"error":"Unauthorized","message":"Bad cr
edentials","path":"/service/echo/hello"}

**Comment by sanjeet2014mca** [comment]
it is possible to implement all configuration of SecuRest & spring-boot-jsonrpc4j in single project..
if Yes then please share that link 
......

**Comment by sothawo** [comment]
the project as it is in this repository comes with two users in the SecurityConfig.java file: 
_user1_ with password _secret1_ and _user2_ with password _secret2_.

There is no default "user" with password "dfd7...." in this sample project.

Your second question: this is a sample project to show how a REST service can be secured within spring boot. If you want to use that as a base to add other libraries you need, you're welcome., but this is nothing what I will add to this sample.

**Comment by sanjeet2014mca** [comment]
Thanks you so much.
But i need one  Rest service Application in that there will be different controller method 
like  passing Credential(UserName,Password) ,calling controller method with parameter values,calling controller method without parameter values, pass request by curl command on windows platform & get response on command prompt.
Thanks in adv....

**Comment by sanjeet2014mca** [comment]
using jsonrpc4j we are able to send the request and get the response sucessfully.
request :
curl -v -H "Content-Type: application/json" -d "{\"id\":0, \"method\":\"sayHelloWorld\", \"params\":[\"John Doe\"]}" http://localhost:8080/rpc/myservice
response : 
{"jsonrpc":"2.0","id":0,"result":"Hello world, John Doe"}

now we want to add head in the same request authentication(username/password)

curl 
-u "jsonrpc:19ffd9709d03ce50675c3a43d1c49c1ac207f4bc45f06c5b2701fbdf8929" 
-d "{\"id\":0, \"method\":\"sayHelloWorld\", \"params\":[\"John Doe\"]}" http://localhost:8080/rpc/myservice

please help us in this..provide any sample code implementation using jsonrpc4j

**Comment by sanjeet2014mca** [comment]
Hi,
I am trying to execute JsonRPC4J application on Ubuntu.
# mvn clean package-->Success 
But at the time of server running i am facing issue pls help me.
# java -jar target/JsonRPC-0.0.1-SNAPSHOT.jar

ERROR 6805 --- [           main] o.a.coyote.http11.Http11NioProtocol      : Failed to start end point associated with ProtocolHandler ["http-nio-8080"]
java.net.BindException:  **Address already in use**
	at sun.nio.ch.Net.bind0(Native Method) ~[na:1.7.0_80]
	at sun.nio.ch.Net.bind(Net.java:463) ~[na:1.7.0_80]
	at sun.nio.ch.Net.bind(Net.java:455) ~[na:1.7.0_80]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[na:1.7.0_80]

**Comment by sothawo** [comment]
this is the wrong place for your question. This is the SecuRest example which has nothing to do with JsonRPC. by the way, the error message is pretty clear: You probably did not stop the last instance you started before restarting.
